#!/usr/bin/env bash

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv"

alias vv='NVIM_APPNAME=nvim-new nvim'

#User chrome in windows
#alias chrome="/mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe"
