#!/usr/bin/env bash

addToPathFront /home/adam/n/bin

addToPath /home/adam/personal/lua-language-server/bin/Linux
addToPath /usr/local/go/bin
addToPath $HOME/.local/bin
addToPath $GOPATH/bin
addToPath $HOME/.yarn/bin
addToPath /mnt/c/Users/abremhol/AppData/Local/Programs/Microsoft\ VS\ Code/bin
addToPath $HOME/.dotnet
addTopath $HOME/.local/share/JetBrains/Toolbox/scripts

# ccache
addToPathFront /usr/lib/ccache
