#!/usr/bin/env bash

addToPathFront /home/adam/n/bin

addToPath $HOME/dotnet
addToPath $HOME/.dotnet/tools
addToPath /usr/local/go/bin
addToPath $HOME/.local/bin
addToPath $GOPATH/bin
addToPath $HOME/.yarn/bin
addToPath /mnt/c/Users/abremhol/AppData/Local/Programs/Microsoft\ VS\ Code/bin

# ccache
addToPathFront /usr/lib/ccache
